name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-20.04
            python-version: "3.8"
            pyinstaller: yes
          - os: ubuntu-20.04
            python-version: "3.9"
          - os: ubuntu-20.04
            python-version: "3.10"
          - os: ubuntu-20.04
            python-version: "3.11"
          - os: ubuntu-20.04
            python-version: "3.12"

          # Mac
          - os: macos-12
            python-version: "3.8"
            pyinstaller: yes

          # Windows
          - os: windows-latest
            python-version: "3.8"
            pyinstaller: yes

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run linter & unit tests
        run: make

      - name: Testing pyinstaller build
        if: ${{ matrix.pyinstaller }}
        run: |
          make pyinstaller
          ./dist/minet/minet --version
